name: 'Test and build'

on:
  push:
    branches:
      - '**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm ci install

      - name: Build
        run: pnpm run build
